-- ============================================
-- Quran Tadabbur
-- Lifetime Access + Opinion/Dua
-- ============================================

-- 1. Create feedback table
create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  feedback text not null,
  created_at timestamptz not null default now()
);


-- 2. Enable Row Level Security
alter table public.user_feedback
enable row level security;


-- 3. Remove old policies if they exist
drop policy if exists "Users can submit their own feedback"
on public.user_feedback;

drop policy if exists "Only admins can view feedback"
on public.user_feedback;


-- 4. Remove broad table access
revoke all on table public.user_feedback
from anon, authenticated;


-- 5. Allow authenticated users to INSERT
--    only for their own user_id
create policy "Users can submit their own feedback"
on public.user_feedback
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
);


-- 6. Allow ONLY admins to SELECT feedback
create policy "Only admins can view feedback"
on public.user_feedback
for select
to authenticated
using (
  (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);


-- 7. Grant required table permissions
grant insert, select
on table public.user_feedback
to authenticated;


-- 8. Function to capture signup Opinion/Dua
create or replace function public.capture_signup_feedback()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  feedback_value text;
begin

  feedback_value :=
    new.raw_user_meta_data ->> 'signup_feedback';

  if feedback_value is not null
     and length(trim(feedback_value)) > 0 then

    insert into public.user_feedback (
      user_id,
      email,
      feedback
    )
    values (
      new.id,
      new.email,
      left(trim(feedback_value), 1000)
    );

  end if;

  return new;
end;
$$;


-- 9. Recreate the Auth trigger safely
drop trigger if exists "capture_signup_feedback"
on auth.users;


create trigger "capture_signup_feedback"
after insert on auth.users
for each row
execute function public.capture_signup_feedback();


-- ============================================
-- IMPORTANT
-- ============================================
-- Admin role will be assigned separately
-- after we confirm this SQL runs successfully.
--
-- NEVER put a Supabase service_role/secret key
-- inside the website frontend.
