-- Quran Tadabbur: Lifetime Access Opinion / Dua + Personal Dashboard
-- Run this once in Supabase SQL Editor.
-- IMPORTANT: Replace YOUR_ADMIN_EMAIL with your own account email in the final UPDATE.

create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  feedback text not null,
  created_at timestamptz not null default now()
);

alter table public.user_feedback enable row level security;

revoke all on table public.user_feedback from anon;
grant insert on table public.user_feedback to authenticated;
grant select on table public.user_feedback to authenticated;

-- A signed-in user may submit feedback only for their own account.
create policy if not exists "Users can submit their own feedback"
on public.user_feedback for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- Only an account whose app_metadata role is admin can read submissions.
create policy if not exists "Only admins can read feedback"
on public.user_feedback for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Copy the required signup feedback from auth user metadata into the protected table.
create or replace function public.capture_signup_feedback()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new.raw_user_meta_data ->> 'signup_feedback', '') <> '' then
    insert into public.user_feedback (user_id, email, feedback)
    values (new.id, new.email, new.raw_user_meta_data ->> 'signup_feedback');
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_feedback on auth.users;
create trigger on_auth_user_created_feedback
after insert on auth.users
for each row execute procedure public.capture_signup_feedback();

-- Make your own account an admin AFTER you have created it.
-- Replace the email below with your own email and run this separately.
-- update auth.users
-- set raw_app_meta_data = jsonb_set(coalesce(raw_app_meta_data, '{}'::jsonb), '{role}', '"admin"'::jsonb)
-- where email = 'YOUR_ADMIN_EMAIL';

-- Never put a Supabase service_role/secret key in the website frontend.
