-- Quran Tadabbur: Monthly Tadabbur recognition
-- Run once in Supabase SQL Editor.
-- Counts at most ONE Tadabbur per Ayah per user per calendar month.
-- The previous month's winner is shown on the homepage during days 1-3 of the new month.

create table if not exists public.tadabbur_monthly_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month_key text not null,
  ayah_key text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  unique(user_id, month_key, ayah_key)
);

alter table public.tadabbur_monthly_entries enable row level security;
revoke all on table public.tadabbur_monthly_entries from anon, authenticated;

create or replace function public.record_tadabbur_entry(p_ayah_key text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  month_value text := to_char(now() at time zone 'Asia/Dhaka', 'YYYY-MM');
  display_value text;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  -- Accept only the app's Surah/index key shape, e.g. surah-2:0.
  if p_ayah_key is null or p_ayah_key !~ '^surah-[0-9]{1,3}:[0-9]{1,3}$' then
    raise exception 'Invalid Ayah key';
  end if;

  select coalesce(nullif(trim(raw_user_meta_data ->> 'display_name'), ''), split_part(email, '@', 1), 'Quran Tadabbur User')
    into display_value
    from auth.users
   where id = uid;

  insert into public.tadabbur_monthly_entries(user_id, month_key, ayah_key, display_name)
  values(uid, month_value, p_ayah_key, left(display_value, 80))
  on conflict (user_id, month_key, ayah_key) do nothing;
end;
$$;

create or replace function public.get_tadabbur_of_month()
returns table(display_name text, count bigint, kicker text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  today_local date := (now() at time zone 'Asia/Dhaka')::date;
  previous_month text := to_char(today_local - interval '1 month', 'YYYY-MM');
  current_month text := to_char(today_local, 'YYYY-MM');
begin
  -- Recognition is shown only on the first three days of each month.
  if extract(day from today_local) > 3 then
    return;
  end if;

  return query
  select e.display_name, count(*)::bigint,
         'Tadabbur of the Month'::text
    from public.tadabbur_monthly_entries e
   where e.month_key = previous_month
   group by e.user_id, e.display_name
   order by count(*) desc, min(e.created_at) asc
   limit 1;
end;
$$;

revoke all on function public.record_tadabbur_entry(text) from public;
grant execute on function public.record_tadabbur_entry(text) to authenticated;

revoke all on function public.get_tadabbur_of_month() from public;
grant execute on function public.get_tadabbur_of_month() to anon, authenticated;

create index if not exists tadabbur_monthly_entries_month_idx
  on public.tadabbur_monthly_entries(month_key, created_at);

-- No service_role/secret key belongs in the frontend.
